api_platform:
    title: Reddit-Ish API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        http_auth:
            JWT:
                scheme: bearer
                bearerFormat: JWT
