# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_secure: 'auto'
    html_sanitizer:
        sanitizers:
            app.post_sanitizer:
                allow_elements:
                - h1

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
