framework:
    rate_limiter:
        registration:
            policy: 'sliding_window'
            limit: 50
            interval: '1 hour'

        api_topic_list:
            policy: 'sliding_window'
            limit: 30
            interval: '1 minute'
